name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# Minimal permissions by default
permissions:
  contents: read

jobs:
  main:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          # Use the volta.node property as the source of truth
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with lerna-lite
        run: lerna run test
